version: "3"
services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    image: producer:1.0
    container_name: producer
    ports:
    - 8282:8282
    volumes:
    - logfolder:/log
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    image: consumer:1.0
    container_name: consumer
    volumes:
    - logfolder:/log
    depends_on:
    - producer
    environment:
      host: producer
      port: 8282
volumes:
  logfolder:
